tasks:
  - name: Unzip project
    init: |
      sudo apt-get update
      sudo apt-get install -y unzip
      unzip OverlayHUD_FinalComplete2.zip -d project
      mv project/* .
      rm -rf project OverlayHUD_FinalComplete2.zip
