tasks:
  - name: Unzip project
    init: |
      sudo apt-get update
      sudo apt-get install -y unzip
      unzip OverlayHUD_Final_Gitpod_v2.zip -d project
      mv project/* .
      rm -rf project OverlayHUD_Final_Gitpod_v2.zip
