tasks:
  - name: Unzip project
    init: |
      sudo apt-get update
      sudo apt-get install -y unzip
      unzip OverlayWASD.zip -d project
      mv project/* .
      rm -rf project OverlayWASD.zip
